### ISSUE TITLE
geolocation implementation breaks developer options/mock location 

### ISSUE THREAD

**Issue by TimoGoetze** [GrapheneOS/grapheneos.org#506]
while developing I experienced that it is not possible to mock the gps location as in original AOSP. No mock location provider is working. Most crash with strange stacktraces like for example

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.220624.021/2022083000:user/release-keys
package: com.wesaphzt.privatelocation:4
process: com.wesaphzt.privatelocation

java.lang.RuntimeException: Unable to start service com.wesaphzt.privatelocation.service.LocationService@c658872 with Intent { act=ACTION_STOP_FOREGROUND_SERVICE cmp=com.wesaphzt.privatelocation/.service.LocationService }: java.lang.SecurityException: Not allowed to delete channel location_notification_channel_id with a foreground service
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4709)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2182)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: Not allowed to delete channel location_notification_channel_id with a foreground service
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3012)
	at android.os.Parcel.createException(Parcel.java:2996)
	at android.os.Parcel.readException(Parcel.java:2979)
	at android.os.Parcel.readException(Parcel.java:2921)
	at android.app.INotificationManager$Stub$Proxy.deleteNotificationChannel(INotificationManager.java:3777)
	at android.app.NotificationManager.deleteNotificationChannel(NotificationManager.java:1003)
	at com.wesaphzt.privatelocation.service.LocationService.shutdown(LocationService.java:206)
	at com.wesaphzt.privatelocation.service.LocationService.onStartCommand(LocationService.java:91)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4691)
	... 11 more

```

or 

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.220624.021/2022083000:user/release-keys
package: cl.coders.faketraveler:7
process: cl.coders.faketraveler

java.lang.IllegalStateException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:2996)
	at android.os.Parcel.readException(Parcel.java:2979)
	at android.os.Parcel.readException(Parcel.java:2921)
	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:2154)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2113)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2088)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2062)
	at cl.coders.faketraveler.MockLocationProvider.<init>(MockLocationProvider.java:28)
	at cl.coders.faketraveler.MainActivity.applyLocation(MainActivity.java:257)
	at cl.coders.faketraveler.MainActivity$1.onClick(MainActivity.java:81)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:200)
	at com.android.server.location.LocationManagerService.addLocationProviderManager(LocationManagerService.java:350)
	at com.android.server.location.LocationManagerService.getOrAddLocationProviderManager(LocationManagerService.java:342)
	at com.android.server.location.LocationManagerService.addTestProvider(LocationManagerService.java:1314)


```

when starting to mock a location. 

I have a pixel 6, all up to date. I tried both using the location routing and sandboxed play service location services. Both same behaviour.

Thanks for some ideas. I would like to keep using my new pixel with graphene when developing.

**Comment by thestinger** [comment]
These are apps bugs, not a GrapheneOS issue. These apps probably have bugs breaking them on modern Android.
