### ISSUE TITLE
Office apk can't update

### ISSUE THREAD

**Issue by Justikhan** [GrapheneOS/grapheneos.org#520]
type: crash
osVersion: google/bramble/bramble:13/TP1A.220905.004/2022092300:user/release-keys
package: com.android.vending:83111410
process: com.android.vending

java.lang.IllegalStateException: This method must be called from the UI thread.
 at xnp.c(PG:2)
 at xmu.h(Unknown Source:0)
 at och.a(Unknown Source:2)
 at etm.j(Unknown Source:14)
 at etm.k(PG:1)
 at etm.e(Unknown Source:0)
 at ome.aN(PG:3)
 at ome.D(PG:5)
 at kwi.Q(PG:3)
 at kwi.D(PG:10)
 at kwi.y(PG:12)
 at aym.R(PG:5)
 at kvx.accept(PG:4)
 at iuv.b(Unknown Source:2)
 at afzd.run(PG:6)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at iuj.run(PG:31)
 at java.lang.Thread.run(Thread.java:1012)

**Comment by Justikhan** [comment]
Anyone have the same problem?
