### ISSUE TITLE
Keyboard keep stopping 

### ISSUE THREAD

**Issue by heilcheng** [GrapheneOS/grapheneos.org#822]
Keyboard keep stopping after the newest system update.
Model: Pixel 6 Pro

```
type: crash
osVersion: google/raven/raven:14/UQ1A.231205.015/2023123000:user/release-keys
package: com.android.inputmethod.latin:30
process: com.android.inputmethod.latin
processUptime: 72 + 306 ms

java.lang.RuntimeException: Unable to create service com.android.inputmethod.latin.spellcheck.AndroidSpellCheckerService: java.lang.RuntimeException: RichInputMethodManager is used before initialization
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4701)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2276)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.RuntimeException: RichInputMethodManager is used before initialization
	at com.android.inputmethod.latin.RichInputMethodManager.checkInitialized(RichInputMethodManager.java:90)
	at com.android.inputmethod.latin.RichInputMethodManager.getInstance(RichInputMethodManager.java:76)
	at com.android.inputmethod.latin.spellcheck.AndroidSpellCheckerService.fetchEnabledLocales(AndroidSpellCheckerService.java:125)
	at com.android.inputmethod.latin.spellcheck.AndroidSpellCheckerService.onCreate(AndroidSpellCheckerService.java:111)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4688)
	... 11 more

```

**Comment by thestinger** [comment]
Update to the latest release.
